// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -package example_test -destination mocks_test.go
//

// Package example_test is a generated GoMock package.
package example_test

import (
	context "context"
	example "go-boilerplate/internal/domain/example"
	example0 "go-boilerplate/internal/model/example"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockexamples is a mock of examples interface.
type Mockexamples struct {
	ctrl     *gomock.Controller
	recorder *MockexamplesMockRecorder
}

// MockexamplesMockRecorder is the mock recorder for Mockexamples.
type MockexamplesMockRecorder struct {
	mock *Mockexamples
}

// NewMockexamples creates a new mock instance.
func NewMockexamples(ctrl *gomock.Controller) *Mockexamples {
	mock := &Mockexamples{ctrl: ctrl}
	mock.recorder = &MockexamplesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockexamples) EXPECT() *MockexamplesMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *Mockexamples) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockexamplesMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*Mockexamples)(nil).Count), ctx)
}

// List mocks base method.
func (m *Mockexamples) List(ctx context.Context, input example0.ListInput) ([]*example.Example, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].([]*example.Example)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockexamplesMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockexamples)(nil).List), ctx, input)
}
