// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -package example_test -destination mocks_test.go
//

// Package example_test is a generated GoMock package.
package example_test

import (
	context "context"
	example "go-boilerplate/internal/model/example"
	example0 "go-boilerplate/internal/presenter/example"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockusecase is a mock of usecase interface.
type Mockusecase struct {
	ctrl     *gomock.Controller
	recorder *MockusecaseMockRecorder
}

// MockusecaseMockRecorder is the mock recorder for Mockusecase.
type MockusecaseMockRecorder struct {
	mock *Mockusecase
}

// NewMockusecase creates a new mock instance.
func NewMockusecase(ctrl *gomock.Controller) *Mockusecase {
	mock := &Mockusecase{ctrl: ctrl}
	mock.recorder = &MockusecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockusecase) EXPECT() *MockusecaseMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *Mockusecase) List(ctx context.Context, input example.ListInput) (example.ListOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].(example.ListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockusecaseMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockusecase)(nil).List), ctx, input)
}

// Mockpresenter is a mock of presenter interface.
type Mockpresenter struct {
	ctrl     *gomock.Controller
	recorder *MockpresenterMockRecorder
}

// MockpresenterMockRecorder is the mock recorder for Mockpresenter.
type MockpresenterMockRecorder struct {
	mock *Mockpresenter
}

// NewMockpresenter creates a new mock instance.
func NewMockpresenter(ctrl *gomock.Controller) *Mockpresenter {
	mock := &Mockpresenter{ctrl: ctrl}
	mock.recorder = &MockpresenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockpresenter) EXPECT() *MockpresenterMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *Mockpresenter) List(output example.ListOutput) example0.ListResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", output)
	ret0, _ := ret[0].(example0.ListResponse)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockpresenterMockRecorder) List(output any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockpresenter)(nil).List), output)
}
